version: '2'

services:
  db:
    image: postgres:9.5
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data

  django:
    image: madron/progettificio
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - media:/media
    depends_on:
      - "db"
    links:
      - "db:db"
    ports:
      - "0.0.0.0:8080:8000/tcp"

  nginx:
    image: madron/progettificio
    volumes:
      - media:/media
    depends_on:
      - "django"
    links:
      - "django:django"
    ports:
      - "0.0.0.0:80:80/tcp"
    command: nginx


volumes:
  db:
    driver: local
  media:
    driver: local
