# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 11:20
from __future__ import unicode_literals

import association.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='number')),
                ('first_name', models.CharField(db_index=True, default=b'', max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(db_index=True, default=b'', max_length=50, verbose_name='last name')),
                ('place_of_birth', models.CharField(default=b'', max_length=50, verbose_name='birth place')),
                ('date_of_birth', models.DateField(verbose_name='birth date')),
                ('city', models.CharField(db_index=True, default=b'', max_length=50, verbose_name='city')),
                ('address', models.CharField(db_index=True, default=b'', max_length=50, verbose_name='address')),
                ('zip_code', models.CharField(default=b'', max_length=10, verbose_name='zip code')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='phone number')),
                ('request_place', models.CharField(default=association.models.default_request_place, max_length=50, verbose_name='request place')),
                ('request_date', models.DateField(default=datetime.date.today, null=True, verbose_name='request date')),
                ('sign', models.BooleanField(db_index=True, default=False, verbose_name='sign')),
                ('approval_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='approval date')),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
                'verbose_name': 'member',
                'verbose_name_plural': 'members',
            },
        ),
        migrations.CreateModel(
            name='ProvisionalMember',
            fields=[
            ],
            options={
                'verbose_name': 'provisional member',
                'proxy': True,
                'verbose_name_plural': 'provisional members',
            },
            bases=('association.member',),
        ),
    ]
