# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 17:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='numero')),
                ('first_name', models.CharField(default=b'', max_length=50, verbose_name='nome')),
                ('last_name', models.CharField(default=b'', max_length=50, verbose_name='cognome')),
                ('place_of_birth', models.CharField(default=b'', max_length=50, verbose_name='luogo di nascita')),
                ('date_of_birth', models.DateField(verbose_name='data di nascita')),
                ('city', models.CharField(default=b'', max_length=50, verbose_name='citt\xe0')),
                ('address', models.CharField(default=b'', max_length=50, verbose_name='indirizzo')),
                ('zip_code', models.CharField(default=b'', max_length=10, verbose_name='cap')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='telefono')),
                ('request_place', models.CharField(default=b'', max_length=50, verbose_name='luogo richiesta')),
                ('request_date', models.DateField(default=datetime.date.today, null=True, verbose_name='data richiesta')),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
                'verbose_name': 'socio',
                'verbose_name_plural': 'soci',
            },
        ),
    ]
